
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $(".tipoFisico").hide();
            $(".tipoJuridico").hide();
            $('input[type=radio][name=tipoPessoa]').change(function () {
                if (this.value === 'fisica') {
                    $(".tipoFisico").show();
                    $(".tipoJuridico").hide();
                }
                else if (this.value === 'juridica') {
                    $(".tipoFisico").hide();
                    $(".tipoJuridico").show();
                }
            });
        });
    </script>


    <title>Acessibilidade</title>

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="css/font-awesome.min.css">
    <link rel="stylesheet" href="css/animate.css">
    <link href="css/animate.min.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet" />

    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

    <style>
        .tipoFisico{
            color:black;
        }
        .tipoJuridico{
            color:black;
        }

        .form-group .form-control{
            border-color: #999;
        }
    </style>

</head>
<body>
<header id="header">
    <nav class="navbar navbar-default navbar-static-top" role="banner">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="navbar-brand">
                    <a href="index.html"><h1>Acessibility</h1></a>
                </div>
            </div>
            <div class="navbar-collapse collapse">
                <div class="menu">
                    <ul class="nav nav-tabs" role="tablist">
                        <li role="presentation"><a href="index.html">Home</a></li>
                        <li role="presentation"><a href="sobre.html">Sobre</a></li>
                        <li role="presentation"><a href="tipos.html">Tipos</a></li>
                        <li role="presentation"><a href="login.phtml">Login</a></li>
                        <li role="presentation"><a href="cadastro.phtml" class="active">Cadastre-se</a></li>
                    </ul>
                </div>
            </div>
        </div><!--/.container-->
    </nav><!--/nav-->
</header><!--/header-->


<section class="contact-page">
    <div class="container">

        <div class="text-center">
            <h2>Cadastre-se</h2>
        </div>

        <div class="row contact-wrap">
            <div class="status alert alert-success" style="display: none"></div>

            <form id="main-contact-form" style="margin-bottom: 20%; margin-top: 10%" class="contact-form" name="contact-form" method="post" action="controlador/cadastro.php">

                <div class="col-sm-5 col-sm-offset-1">
                    <div class="form-group">
                        <label>Nome *</label>
                        <input type="text" name="nome" class="form-control" required="required">
                    </div>
                    <div class="form-group">
                        <label>Email *</label>
                        <input type="email" name="email" class="form-control" required="required">
                    </div>
                    <div class="form-group">
                        <label>Senha *</label>
                        <input name="senha" type="password" class="form-control">
                    </div>
                </div>

                <div class="col-sm-5">
                    <div class="form-group">
                        <label>Você é um usuário:
                        </label>
                    </div>
                </div>
                <br>
                <div class="form-group">
                    <br>
                    <label> Físico  <input id="campoFisica" class="form-control" type="radio" name="tipoPessoa" value="fisica"> </label>
                    <label> Jurídico<input id="campoJuridica" class="form-control" type="radio" name="tipoPessoa" value="juridica"> </label>
                </div>
                <div class="form-group">
                    <input class="tipoFisico" type="text" name="cpf" placeholder="Digite seu CPF">

                    <label class="tipoFisico">Tipo de acessibilidade</label>
                    <select class="tipoFisico" name="especificacao" size="1">
                        <option>Selecione</option>
                        <option>Andador</option>
                        <option>Bengala</option>
                        <option>Cadeira de rodas manual</option>
                        <option>Cadeira motorizada</option>
                        <option>Muleta Auxiliar</option>
                    </select>

                </div>

                <div class="form-group">

                    <input class="tipoJuridico" type="text" name="razao_social" placeholder="Nome da empresa">
                    <input class="tipoJuridico" type="text" name="cnpj" placeholder="Digite o CNPJ">
                </div>


                <div class="form-group">
                    <button type="submit" name="submit" class="btn btn-primary btn-lg" required="required">Cadastrar</button>
                </div>
        </div>
        </form>
    </div><!--/.row-->
    </div><!--/.container-->
</section><!--/#contact-page-->

<footer>

</footer>

<div class="sub-footer">
    <div class="container">
        <div class="social-icon">
            <div class="col-md-4">
                <ul class="social-network">
                    <li><a href="#" class="fb tool-tip" title="Facebook"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="#" class="twitter tool-tip" title="Twitter"><i class="fa fa-twitter"></i></a></li>
                    <li><a href="#" class="gplus tool-tip" title="Google Plus"><i class="fa fa-google-plus"></i></a></li>
                    <li><a href="#" class="linkedin tool-tip" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
                    <li><a href="#" class="ytube tool-tip" title="You Tube"><i class="fa fa-youtube-play"></i></a></li>
                </ul>
            </div> <!-- /class col-md-4 -->
        </div> <!-- /class ssocial-icon -->
    </div>	<!-- /class container -->
</div> <!-- /class sub-footer -->

</body>
</html>